from sqlalchemy import Column, String, Integer
from sqlalchemy.ext.declarative import declarative_base

Base = declarative_base()


class Analytics(Base):
    __tablename__ = 'grandmed_qms_analytics'

    id = Column(Integer, primary_key=True)
    registration_number = Column(String, nullable=True, comment='Рег.№')
    full_name = Column(String, nullable=True, comment='ФИО')
    gender = Column(String, nullable=True, comment='Пол')
    age = Column(String, nullable=True, comment='Возр.')
    okmu_code = Column(String, nullable=True, comment='Код ОКМУ')
    service = Column(String, nullable=True, comment='Услуга')
    first_name = Column(String, nullable=True, comment='Имя')
    last_name = Column(String, nullable=True, comment='Фамилия')
    phone = Column(String, nullable=True, comment='Телефон')
    admission_type = Column(String, nullable=True, comment='Вид поступления')
    admission_purpose = Column(String, nullable=True, comment='Цель поступления')
    episode_number = Column(String, nullable=True, comment='№_эпизода')
    appointment_type = Column(String, nullable=True, comment='Тип назначения')
    appointment_date = Column(String, nullable=True, comment='Дата выполнения назначения')
    appointment_time = Column(String, nullable=True, comment='Время назначения')
    underperformance = Column(String, nullable=True, comment='Недовыполнение')
    status = Column(String, nullable=True, comment='Состояние')
    cd = Column(String, nullable=True, comment='КД')
    bed_days = Column(String, nullable=True, comment='Количество койко-дней (по услуге пребывания в стационаре) за поисковый период')
    department_execution = Column(String, nullable=True, comment='Отделение.Выполнение')
    position_execution = Column(String, nullable=True, comment='Должность.Выполнение')
    specialist_execution = Column(String, nullable=True, comment='Специалист/Ресурс.Выполнение')
    specialist_specialization = Column(String, nullable=True, comment='Специализация исполнителя')
    hospitalization_department = Column(String, nullable=True, comment='Отделение госпитализации')
    tariff = Column(String, nullable=True, comment='Тариф')
    price = Column(String, nullable=True, comment='Цена')
    discount_percent = Column(String, nullable=True, comment='%Ск-ки')
    total_amount = Column(String, nullable=True, comment='Сумма')
    debt = Column(String, nullable=True, comment='Долг')
    specialist_full_name = Column(String, nullable=True, comment='ФИО специалист')
    attending_physician = Column(String, nullable=True, comment='Лечащий врач')
    complex_code = Column(String, nullable=True, comment='Код комплекса')
    price_section = Column(String, nullable=True, comment='Раздел прайса на дату, когда услуга была назначена')
    service_code = Column(String, nullable=True, comment='Код услуги по прайсу на дату, когда услуга была назначена')
    category = Column(String, nullable=True, comment='Категория')
    execution_time = Column(String, nullable=True, comment='Время выполнения')
    set_indicator = Column(String, nullable=True, comment='Признак набора')
    physician_department_code = Column(String, nullable=True, comment='Код отделения лечащего врача')
    physician_department = Column(String, nullable=True, comment='Лечащий врач: код отделения')
    registration_number_alt = Column(String, nullable=True, comment='Рег.№.1')
    email = Column(String, nullable=True, comment='Электронная почта')
    middle_name = Column(String, nullable=True, comment='Отчество')
    episode_end_date = Column(String, nullable=True, comment='Дата завершения эпизода')
    date = Column(String, nullable=True, comment='Дата')
    birth_date = Column(String, nullable=True, comment='ДР')
    paid_destination_num = Column(String, nullable=True, comment='Номер оплачиваемого назначения')
    instance_code = Column(String, nullable=True, comment='%Код экземпляра')


class Specialists(Base):
    __tablename__ = 'grandmed_qms_specialists'

    id = Column(Integer, primary_key=True)
    material_number = Column(String, unique=True, comment='Номер материала')
    patient_type = Column(String, comment='Вид пациента')
    oocyte_assessment = Column(String, comment='Оценка ооцита')
    fertilization_method = Column(String, comment='Метод оплодотворения')
    sperm_processing = Column(String, comment='Обработка спермы')
    fertilization_assessment = Column(String, comment='Оценка оплодотворения')
    development_medium = Column(String, comment='Среда для развития')
    incubator = Column(String, comment='Инкубатор')
    date_d0 = Column(String, comment='Дата D0')
    embryologist = Column(String, comment='Эмбриолог')
    attending_physician = Column(String, comment='Лечащий врач')
    episode_number = Column(String, comment='Номер эпизода')
    registration_number = Column(String, comment='Рег.№')
    patient_age = Column(String, comment='Возраст пациента')
    development_medium_alt = Column(String, comment='Среда для развития.')
