from sqlalchemy import Column, String, Integer
from sqlalchemy.ext.declarative import declarative_base

Base = declarative_base()


class Analytics(Base):
    __tablename__ = 'grandmed_analytics'

    id = Column(Integer, primary_key=True, autoincrement=True, comment="Уникальный идентификатор записи")

    reg_number = Column(String(50), comment="Рег.№")
    fio = Column(String(200), comment="ФИО")
    gender = Column(String(10), comment="Пол")
    age = Column(String(20), comment="Возр.")
    okmu_code = Column(String(50), comment="Код ОКМУ")
    service = Column(String(500), comment="Услуга")
    first_name = Column(String(100), comment="Имя")
    last_name = Column(String(100), comment="Фамилия")
    phone = Column(String(20), comment="Телефон")
    admission_type = Column(String(100), comment="Вид поступления")
    purpose = Column(String(100), comment="Цель поступления")
    episode_number = Column(String(100), comment="№_эпизода")
    assignment_type = Column(String(100), comment="Тип назначения")
    episode_end_date = Column(String(50), comment="Дата завершения эпизода")
    assignment_date = Column(String(50), comment="Дата выполнения назначения")
    assignment_time = Column(String(50), comment="Время назначения")
    non_completion = Column(String(50), comment="Недовыполнение")
    status = Column(String(50), comment="Состояние")
    kd = Column(String(10), comment="КД")
    bed_days = Column(String, comment="Количество койко-дней (по услуге пребывания в стационаре) за поисковый период")
    department_execution = Column(String(100), comment="Отделение.Выполнение")
    position_execution = Column(String(200), comment="Должность.Выполнение")
    specialist_execution = Column(String(200), comment="Специалист/Ресурс.Выполнение")
    specialization = Column(String(200), comment="Специализация исполнителя")
    hospitalization_department = Column(String(100), comment="Отделение госпитализации")
    tariff = Column(String(10), comment="Тариф")
    price = Column(String, comment="Цена")
    discount_percent = Column(String, comment="%Ск-ки")
    amount = Column(String, comment="Сумма")
    debt = Column(String, comment="Долг")
    date = Column(String(50), comment="Дата")
    specialist_fio = Column(String(200), comment="ФИО специалист")
    attending_doctor = Column(String(300), comment="Лечащий врач")
    complex_code = Column(String(50), comment="Код комплекса")
    price_section = Column(String(300), comment="Раздел прайса на дату, когда услуга была назначена")
    price_code = Column(String(50), comment="Код услуги по прайсу на дату, когда услуга была назначена")
    category = Column(String(100), comment="Категория")
    execution_time = Column(String(50), comment="Время выполнения")
    set_sign = Column(String(50), comment="Признак набора")
    doctor_department_code = Column(String(50), comment="Код отделения лечащего врача")
    attending_doctor_department_code = Column(String(50), comment="Лечащий врач: код отделения")
    reg_number_duplicate = Column(String(50), comment="Рег.№")
    email = Column(String(100), comment="Электронная почта")
    patronymic = Column(String(100), comment="Отчество")
    birth_date = Column(String(50), comment="ДР")
    patient_category = Column(String(100), comment="Категория пациента")


class Specialists(Base):
    __tablename__ = 'grandmed_specialists'

    id = Column(Integer, primary_key=True, autoincrement=True, comment="Уникальный идентификатор записи")

    record_number = Column(String, comment="№")
    material_number = Column(String(100), comment="Номер материала")
    patient_type = Column(String(50), comment="Вид пациента")
    oocyte_grade = Column(String(20), comment="Оценка ооцита")
    fertilization_method = Column(String(50), comment="Метод оплодотворения")
    sperm_preparation = Column(String(100), comment="Обработка спермы")
    fertilization_result = Column(String(20), comment="Оценка оплодотворения")
    culture_medium = Column(String(200), comment="Среда для развития")
    incubator = Column(String(50), comment="Инкубатор")
    d0_date = Column(String(50), comment="Дата D0")
    embryologist = Column(String(200), comment="Эмбриолог")
    attending_doctor = Column(String(200), comment="Лечащий врач")
    episode_number = Column(String(100), comment="Номер эпизода")
    reg_number = Column(String(50), comment="Рег.№")
    patient_age = Column(String(20), comment="Возраст пациента")
    culture_medium_duplicate = Column(String(200), comment="Среда для развития")
